Parameters:
  AppName: "cs_itpro_s3website001"

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AppName}-${AWS::Region}-${AWS::AccountId}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      WebsiteConfiguration:
        IndexDocument: index.html

#   Distribution:
#     Type: AWS::CloudFront::Distribution
#     Properties:
#       DistributionConfig:
#         Origins:
#           - DomainName: !GetAtt WebsiteBucket.RegionalDomainName
#             Id: Origin1
#             S3OriginConfig:
#               OriginAccessIdentity: ""
#         DefaultCacheBehavior:
#           TargetOriginId: Origin1
#           ViewerProtocolPolicy: redirect-to-https
#         Enabled: true

# Outputs:
#   SiteURL:
#     Value: !Sub https://${Distribution.DomainName}
