Parameters:
  AppName: 
    Type: String
    Default: "cs-itpro-s3web"

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AppName}-${AWS::Region}-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html

#   Distribution:
#     Type: AWS::CloudFront::Distribution
#     Properties:
#       DistributionConfig:
#         Origins:
#           - DomainName: !GetAtt WebsiteBucket.RegionalDomainName
#             Id: Origin1
#             S3OriginConfig:
#               OriginAccessIdentity: ""
#         DefaultCacheBehavior:
#           TargetOriginId: Origin1
#           ViewerProtocolPolicy: redirect-to-https
#         Enabled: true

# Outputs:
#   SiteURL:
#     Value: !Sub https://${Distribution.DomainName}
